services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV=true
      - VAULT_DEV_ROOT_TOKEN_ID=root
